home/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm


from . import views

app_name = 'home'
urlpatterns = [
    # /home/interview_questions
    url(r'^interview_questions/$', views.InterviewView.as_view(), name='interview_questions'),

    url(r'^(?P<pk>[0-9]+)/$', views.SingleQuestionView.as_view(), name='detail'),


    # added

    # url(r'^$', views.home_page, name='index'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^register/complete/$', views.registration_complete, name='registration_complete'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views


from django.contrib import admin
admin.autodiscover()




urlpatterns = [

        # AUTH
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, name='logout'),
        url(r'^accounts/register/$', views.register, name='register'),
        url(r'^accounts/register/complete/$', views.registration_complete, name='registration_complete'),
        url(r'^oauth/', include('social_django.urls', namespace='social')),


        # KICKBALL
        url(r'^kickball/$', views.kickball, name='kickball'),
        url(r'^captains/$', views.captains, name='captains'),
        url(r'^reg_kickball/$', views.reg_kickball, name='reg_kickball'),
        # url(r'^season/$', views.SeasonSelect.as_view(), name='season_select'),
        url(r'^reg_kickball/payment/$', views.payment, name='payment'),


        # APPS
        url(r'^admin/', admin.site.urls),
        url(r'^polls/', include('polls.urls')),
        url(r'^home/', include('home.urls')),

        # HOME
        url(r'$', views.home_page, name='index'),

        # OTHER
        url(r'^chaining/', include('smart_selects.urls')),
        url(r'^paypal/', include('paypal.standard.ipn.urls')),
]

home/models.py
from django.db import models
from django.utils import timezone
from django.http import request

from django.contrib.auth import get_user_model
import uuid
User = get_user_model()
# Create your models here.

from smart_selects.db_fields import ChainedForeignKey, GroupedForeignKey



class Season(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()
    location = models.CharField(max_length=55)
    registration_open = models.BooleanField(default=False)
    price = models.IntegerField(default=65)


    class Meta:
        app_label = 'home'

    def current_season(self):
        now = timezone.now()
        return self.start_date <= now <= self.end_date

    def __str__(self):
        return self.location



class Team(models.Model):
    league = models.ForeignKey(Season)
    team_name= models.CharField(max_length=55)
    wins = models.IntegerField(blank = True, default = '0')
    losses = models.IntegerField(blank = True, default= '0')
    ties = models.IntegerField(blank = True, default = '0')
    runs_allowed = models.IntegerField(blank = True, default='0')
    runs_scored = models.IntegerField(default='0', blank = True)
    approved = models.BooleanField(default=True)

    class Meta:
        app_label = 'home'

    def __str__(self):
        return self.team_name

    def __unicode__(self):
        return self.name

shirt_size_choices= (
    ('S','Small'),
    ('M', 'Medium'),
    ('L','Large'),
    ('XL','XLarge'),
    ('XXL','XXLarge'),
)


class Player(models.Model):
    player_username = models.ForeignKey(User, null=True, blank=True)
    player_league = models.ForeignKey(Season, null=True, blank=True)
    player_team = GroupedForeignKey(Team,'league', null=True)

    # player_team = ChainedForeignKey(Team,
    #     blank=True,
    #     null=True,
    #     chained_field='team_name',
    #     chained_model_field='player_team',
    #     show_all=False,
    #     auto_choose=True,
    #     sort=True
    # )

    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    email = models.EmailField()
    picture = models.ImageField(blank = True)
    shirt_size = models.CharField(max_length=25, choices = shirt_size_choices)
    paid = models.BooleanField(default = False)
    credit = models.BooleanField(default = False)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

    class Meta:
        app_label = 'home'

polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.question_text

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

home/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView


from django.db.models.aggregates import Count
import random
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from django.utils import timezone
from django.template.context_processors import csrf

from polls.models import Question



# Create your views here.





# Create your views here.

# def home_page(request):
#     return render(request, 'home/index.html')
#
#

class InterviewView(generic.ListView):
    model = Question
    template_name='home/interview_questions.html'

    def get_context_data(self, **kwargs):
        context = super(InterviewView, self).get_context_data(**kwargs)
        context['random_question_list'] = Question.objects.all().order_by('?')[:3]
        context['full_question_list'] = Question.objects.all()
        return context


class SingleQuestionView(generic.DetailView):
    model = Question
    template_name = 'home/single_question.html'

    def get_context_data(self, **kwargs):
        context = super(SingleQuestionView, self).get_context_data(**kwargs)
        context['all_questions'] = Question.objects.all()
        return context



# def register(request):
#     form = UserCreationForm(request.POST)
#     token = {}
#     token.update(csrf(request))
#     token['form'] = form
#     if request.method == "POST" and form.is_valid():
#         user = super(UserCreationForm, form).save(commit=False)  # changed to True
#         user.set_password(form.cleaned_data["password1"])
#         form.save(commit = True)
#         return user.cleaned_data
#         user.save()
#         return HttpResponseRedirect('/register/complete')
#
#     return render_to_response('registration/registration_form.html', token)
#
#
#
# def registration_complete(request):
#     return render_to_response('registration/registration_complete.html')

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}



 {% block title %} Home Page {% endblock %}



{% block content %}
<div class="container">
Welcome
{% if not user.is_authenticated %}
Guest. Please login or<a href="{% url 'register' %}?next={{ request.path | urlencode }}"> register</a>. Use links in the header to navigate the page.

{% else %}
{{request.user.username}}
{% endif %}

<br>
</div>

{% endblock %}







			

home/templates/home/interview_questions.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


{% if random_question_list %}

<div class="container">
    <div class="panel-heading">
        <h2>Here are a few random questions</h2>
    </div>
</div>



 {% for question in random_question_list %}
<div class="container">

  <ul class="list-group">

    <li class="list-group-item">Q: {{ question }}
    <br>
        {% for choice in question.choice_set.all %}
        A: {{choice.choice_text }}<br>
        {% endfor %}
    </li>

  </ul>
</div>

{% endfor %}


</ul>
{% else %}
<p>No questions loaded.</p>
{% endif %}



<div class="container">
  <h2>Or choose from any question below.</h2>

  <div class="panel-group">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" href="#collapse1">Click Here For More Questions</a>
        </h4>
      </div>
      <div id="collapse1" class="panel-collapse collapse">
        <ul class="list-group">
            {% for question in full_question_list %}
            <li class="list-group-item"><a href="{% url 'home:detail' question.id %}">{{ question }}</a></li>

        </ul>
          {% endfor %}
      </div>
    </div>
  </div>
</div>





{% endblock %}



			

home/templates/home/single_question.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}





<div class="container">
    <div class="panel-heading">
        <h3>{{ question.question_text }}</h3>
    </div>
</div>



{% for choice in question.choice_set.all %}
<div class="container">

  <ul class="list-group">

    <li class="list-group-item">
       {{choice.choice_text}}
    </li>

  </ul>
</div>
{% endfor %}





{% endblock %}



			