home/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.forms import UserCreationForm


from . import views

app_name = 'home'
urlpatterns = [
    # /home/interview_questions
    url(r'^interview_questions/$', views.InterviewView.as_view(), name='interview_questions'),

    url(r'^(?P<pk>[0-9]+)/$', views.SingleQuestionView.as_view(), name='detail'),


    # added

    # url(r'^$', views.home_page, name='index'),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
    # url(r'^register/$', views.register, name='register'),
    # url(r'^register/complete/$', views.registration_complete, name='registration_complete'),

]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib.auth import views as auth_views
from . import views


from django.contrib import admin
admin.autodiscover()




urlpatterns = [

        # AUTH
        url(r'^login/$', auth_views.login, name='login'),
        url(r'^logout/$', auth_views.logout, name='logout'),
        url(r'^accounts/register/$', views.register, name='register'),
        url(r'^accounts/register/complete/$', views.registration_complete, name='registration_complete'),
        url(r'^oauth/', include('social_django.urls', namespace='social')),


        # KICKBALL
        url(r'^kickball/$', views.kickball, name='kickball'),
        url(r'^captains/$', views.captains, name='captains'),
        url(r'^reg_kickball/$', views.reg_kickball, name='reg_kickball'),
        # url(r'^season/$', views.SeasonSelect.as_view(), name='season_select'),
        url(r'^reg_kickball/payment/$', views.payment, name='payment'),


        # APPS
        url(r'^admin/', admin.site.urls),
        url(r'^polls/', include('polls.urls')),
        url(r'^home/', include('home.urls')),

        # HOME
        url(r'$', views.home_page, name='index'),

        # OTHER
        url(r'^chaining/', include('smart_selects.urls')),
        url(r'^paypal/', include('paypal.standard.ipn.urls')),
]

templates/base.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
  <title>Web Application</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


<div style = "background:#5CD5E1 !important">

	<center><br>
	<h1>Django Framework Practice</h1>
  	<p>This web application was a training tool for learning the Django Python web framework.</p>


	<div class="container">

	  <div class="row">

		<div class="col-sm-3">
		<h3><a href = /admin/>Admin</a></h3>
		</div>

		<div class="col-sm-3">
		<h3><a href = "{% url 'reg_kickball' %}">Register</a></h3>
		</div>

		<div class="col-sm-3">
		<h3><a href ="{% url 'captains' %}"> Captains </a></h3>
		</div>

		<div class="col-sm-3">
		{% if not user.is_authenticated %}
		<h3><a href ="{% url 'login' %}">Login</a></h3>
		{% else %}
		<h3><a href="{% url 'logout' %}?next={{ request.path | urlencode }}">Logout</a></h3>
		{% endif %}
		</div>

	  </div>


	</div>
	</center>





	<br><br>

	</div>

 {% block content %}
{% endblock %}



</body>
</html>

templates/base_generic.html
{% load static %}



<!DOCTYPE html>
<html lang="en">
<head>
  <title>Web Application</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


<div style = "background:#5CD5E1 !important">

	<center><br>
	<h1>Welcome To My First Web Application</h1>
  	<p>This web application was a training tool for learning the Django Python web framework.</p>


	<div class="container">

	  <div class="row">

		<div class="col-sm-3">
		<h3><a href ="{% url 'index' %}">Home</a></h3>
		</div>

		<div class="col-sm-3">
		<h3><a href = /admin/>Admin</a></h3>
		</div>

		<div class="col-sm-3">
		<h3><a href ="{% url 'home:interview_questions' %}"> Interview Questions</a></h3>
		</div>

		<div class="col-sm-3">
		{% if not user.is_authenticated %}
		<h3><a href ="{% url 'login' %}">Login</a></h3>
		{% else %}
		<h3><a href="{% url 'logout' %}?next={{ request.path | urlencode }}">Logout</a></h3>
		{% endif %}
		</div>

	  </div>

		<!--<div class = "row">-->

			<!--<div class="col-sm-3">-->
			<!--<h3><a href ="{% url 'kickball' %}">Kickball</a></h3>-->
			<!--</div>-->

		<!--</div>-->
	</div>
	</center>
</div>



	<br><br>

 {% block content %}
            {% endblock %}



</body>
</html>

templates/captains.html
{% extends 'base.html' %}
{% load static %}



 {% block title %} Home Page {% endblock %}



{% block content %}
<div class="container">

 <p> This is the Captains page. It will check for a certain permission before allowing access to this page.
  Not sure what I'd put here, probably standings and other announcements.
  It would detect what league a captain belongs to and display only that page.
  </p>

<br>
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}



 {% block title %} Home Page {% endblock %}



{% block content %}
<br><br>
<div class="container">
Welcome
{% if not user.is_authenticated %}
Guest. Please <a href ="{% url 'login' %}">login</a> or<a href="{% url 'register' %}"> register</a>. Use links in the header to navigate the page.

{% else %}
{{request.user.first_name}}
{% endif %}

<br>


</div>

{% endblock %}







			

templates/kickball.html
{% extends 'base.html' %}
{% load static %}



 {% block title %} Home Page {% endblock %}



{% block content %}
<div class="container">

 <p> This is the kickball page </p>

<br>
</div>

{% endblock %}

templates/payment.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block title %} Play Kickball! {% endblock %}

{% block content %}






<script type="text/javascript">
function HidePaid()
{
    document.getElementById('id_paid').disabled = true
    document.getElementById('id_paid').style.visibility = 'hidden';
    document.getElementById('id_credit').disabled = true
    document.getElementById('id_credit').style.visibility = 'hidden';
    document.getElementById("id_player_team").disabled = true;
}



function check()
{
    document.getElementById("PaidCheck").checked = true;
    document.getElementById('id_paid').disabled = false;
    document.getElementById("id_paid").checked = true;
    document.getElementById('id_paid').disabled = true;
}


function CheckCredit()
{
    document.getElementById('id_credit').disabled = false;
    document.getElementById("id_credit").checked = true;
    document.getElementById('id_credit').disabled = true;
}

function checkForm()
{
    if(CreditCheck.checked)
    {
        confirm('You are registering using a free season credit, confirm?');
        document.getElementById('id_paid').disabled = false;
        document.getElementById('id_credit').disabled = false;
        document.getElementById("id_player_team").disabled = false;
        return true;
    }

    if(!PaidCheck.checked)
    {
        alert('Please complete payment or apply a season credit.');
        return false;
    }


document.getElementById('id_paid').disabled = false;
document.getElementById('id_credit').disabled = false;
document.getElementById("id_player_team").disabled = false;
return true;
}



</script>



<body onload="HidePaid()">
<div class="container">



<h4>
{% if not user.is_authenticated %}
Welcome Guest. Please <a href ="{% url 'login' %}">login</a> or<a href="{% url 'register' %}"> create an account </a>before registering to play.
</h4>

{% else %}
You are registering for {{league}}. The registration price for the season is ${{ price }}.
    Please confirm the information below. To complete payment, please use Paypal checkout below or to use a reffing credit.
    Once payment is complete, click submit to complete registration.
{% endif %}

    <br><br>

{% if user.is_authenticated %}














    <!--PAYPAL STUFF-->
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>

    // Render the PayPal button

    paypal.Button.render({

        // Set your environment

        env: 'sandbox', // sandbox | production

        // PayPal Client IDs - replace with your own
        // Create a PayPal app: https://developer.paypal.com/developer/applications/create

        client: {
            sandbox:    'ARKOJXbs_UPUzSscqgFJzfWbjzBY0Bth3U8L0JF9zjN5Hc8xBPoNN_Ig14D5Ac70aGsDzpdQWUlWcFNR',
            production: '<insert production client id>'
        },

        // Set to 'Pay Now'

        commit: true,

        // Wait for the PayPal button to be clicked

        payment: function() {

            // Make a client-side call to the REST api to create the payment

            return paypal.rest.payment.create(this.props.env, this.props.client, {
                transactions: [
                    {
                        //amount: { total: '0.01', currency: 'USD' }
                        amount: { total: {{price}}, currency: 'USD' }
                    }
                ]
            });
        },

        // Wait for the payment to be authorized by the customer

        onAuthorize: function(data, actions) {

            // Execute the payment

            return actions.payment.execute().then(function() {


                // make sure to do this onLoad, for example jQuery's $()
                check()
                window.alert('Payment complete, please complete registration.');

            });
        }

    }, '#paypal-button-container');
</script>

<!--END PAYPAL STUFF -->


<form method="POST" class = form onsubmit="return checkForm();" onload="OnLoad()">
    {% csrf_token %}
    <!--{{ form.as_p }}-->
    {% bootstrap_form form layout='horizontal' %}

 <div id="paypal-button-container"></div>



    <p>

        Paid: <input type="checkbox" id="PaidCheck" name="PaidCheck" onclick="return false;"> &nbsp; &nbsp;
        Season Credit: <input type="checkbox" id="CreditCheck" onclick="CheckCredit()">  </p>



    {% buttons %}
        <button type="Register" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
    {% endbuttons %}




{% endif %}




<p>  Add team register page, </p>

</div>

</body>
{%endblock %}

templates/registration_kickball.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block title %} Play Kickball! {% endblock %}

{% block content %}

<body onload="HidePaid()">
<div class="container">



<h4>
{% if not user.is_authenticated %}
Please <a href ="{% url 'login' %}">login</a> or<a href="{% url 'register' %}"> create an account </a>before registering to play.
</h4>

{% else %}

{% endif %}

    <br><br>

{% if user.is_authenticated %}







<script type="text/javascript">

function HidePaid()
{
    document.getElementById('id_paid').disabled = true
    document.getElementById('id_paid').style.visibility = 'hidden';
    document.getElementById('id_credit').disabled = true
    document.getElementById('id_credit').style.visibility = 'hidden';

}




</script>





<form method="post" class = form onsubmit="return checkForm();" onload="HidePaid()">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}

    {% buttons %}
        <button type="Register" class="btn btn-primary">
            {% bootstrap_icon "star" %} Continue
        </button>
    {% endbuttons %}




{% endif %}




<p> To do...   Add team register page

</p>

</div>

</body>
{%endblock %}

templates/registration_kickball_bak.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block title %} Play Kickball! {% endblock %}

{% block content %}

<body onload="HidePaid()">
<div class="container">



<h4>  Welcome
{% if not user.is_authenticated %}
Guest. Please <a href ="{% url 'login' %}">login</a> or<a href="{% url 'register' %}"> create an account </a>before registering to play.
</h4>

{% else %}
{{request.user.first_name}}
{% endif %}

    <br><br>

{% if user.is_authenticated %}







<script type="text/javascript">

function HidePaid()
{
    document.getElementById('id_paid').disabled = true
    document.getElementById('id_paid').style.visibility = 'hidden';

}

function checkForm()
{

    if(CreditCheck.checked)
    {
        confirm('You are registering using a free season credit, confirm?');
        return true;
    }

    if(!PaidCheck.checked)
    {
        alert('Please complete payment or apply a season credit.');
        return false;
    }

// validation was successful
document.getElementById('id_paid').disabled = false;
return true;
}


function check() {
    document.getElementById("PaidCheck").checked = true;
    document.getElementById('id_paid').disabled = false;
    document.getElementById("id_paid").checked = true;
    document.getElementById('id_paid').disabled = true;

}


</script>



    <!--PAYPAL STUFF-->
<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>

    // Render the PayPal button

    paypal.Button.render({

        // Set your environment

        env: 'sandbox', // sandbox | production

        // PayPal Client IDs - replace with your own
        // Create a PayPal app: https://developer.paypal.com/developer/applications/create

        client: {
            sandbox:    'ARKOJXbs_UPUzSscqgFJzfWbjzBY0Bth3U8L0JF9zjN5Hc8xBPoNN_Ig14D5Ac70aGsDzpdQWUlWcFNR',
            production: '<insert production client id>'
        },

        // Set to 'Pay Now'

        commit: true,

        // Wait for the PayPal button to be clicked

        payment: function() {

            // Make a client-side call to the REST api to create the payment

            return paypal.rest.payment.create(this.props.env, this.props.client, {
                transactions: [
                    {
                        amount: { total: '0.01', currency: 'USD' }
                    }
                ]
            });
        },

        // Wait for the payment to be authorized by the customer

        onAuthorize: function(data, actions) {

            // Execute the payment

            return actions.payment.execute().then(function() {


                // make sure to do this onLoad, for example jQuery's $()
                check()
                window.alert('Payment complete, please complete registration.');

            });
        }

    }, '#paypal-button-container');
</script>

<!--END PAYPAL STUFF -->


<form method="post" class = form onsubmit="return checkForm();" onload="HidePaid()">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}

 <div id="paypal-button-container"></div>



    <p>

        Paid: <input type="checkbox" id="PaidCheck" name="PaidCheck" onclick="return false;"> &nbsp; &nbsp;
        Season Credit: <input type="checkbox" id="CreditCheck">  </p>



    {% buttons %}
        <button type="Register" class="btn btn-primary">
            {% bootstrap_icon "star" %} Submit
        </button>
    {% endbuttons %}




</form>


{% endif %}




<p> To do...  Make Paid ReadOnly or Hidden or ReadfromCheckbox??. Add team register page, Add price to league model and fetch for checkout

</p>

</div>

</body>
{%endblock %}

templates/season_select.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Play Kickball! {% endblock %}

{% block content %}
<div class="container">


<p><h4>
Welcome
{% if not user.is_authenticated %}
Guest. Please <a href ="{% url 'login' %}">login</a> or<a href="{% url 'register' %}"> create an account </a>before registering to play.

{% else %}
{{request.user.first_name}}.
{% endif %}

{% if user.is_authenticated %}

Please select a league below.
</h4></p>


<p>
    {% for location in upcoming_seasons %}
    {{ location }} <br>
    {% endfor %}
</p>

{% endif %}
    <br>
    <h4><a href="{% url 'reg_kickball' %}"> Bypass </a></h4>



</div>
{%endblock %}